spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Incompatible springfox with actuator -> https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
  datasource:
    url: jdbc:h2:file:./src/main/resources/testDb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true