spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/testDb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true